/*
 * k8s.io/api/admission/v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.sochovsky.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;

/**
 * AdmissionReview describes an admission review request/response.
 */
@Data
@Schema(description = "AdmissionReview describes an admission review request/response.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-04-08T23:27:15.525561+02:00[Europe/Vienna]")
public class V1AdmissionReview {
	@SerializedName("apiVersion")
	private String apiVersion = null;

	@SerializedName("kind")
	private String kind = null;

	@SerializedName("request")
	private V1AdmissionRequest request = null;

	@SerializedName("response")
	private V1AdmissionResponse response = null;

	public V1AdmissionReview apiVersion(String apiVersion) {
		this.apiVersion = apiVersion;
		return this;
	}

	/**
	 * APIVersion defines the versioned schema of this representation of an object.
	 * Servers should convert recognized schemas to the latest internal value, and
	 * may reject unrecognized values. More info:
	 * https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	 * 
	 * @return apiVersion
	 **/
	@Schema(description = "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources")
	public String getApiVersion() {
		return apiVersion;
	}

	public void setApiVersion(String apiVersion) {
		this.apiVersion = apiVersion;
	}

	public V1AdmissionReview kind(String kind) {
		this.kind = kind;
		return this;
	}

	/**
	 * Kind is a string value representing the REST resource this object represents.
	 * Servers may infer this from the endpoint the client submits requests to.
	 * Cannot be updated. In CamelCase. More info:
	 * https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	 * 
	 * @return kind
	 **/
	@Schema(description = "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds")
	public String getKind() {
		return kind;
	}

	public void setKind(String kind) {
		this.kind = kind;
	}

	public V1AdmissionReview request(V1AdmissionRequest request) {
		this.request = request;
		return this;
	}

	/**
	 * Get request
	 * 
	 * @return request
	 **/
	@Schema(description = "")
	public V1AdmissionRequest getRequest() {
		return request;
	}

	public void setRequest(V1AdmissionRequest request) {
		this.request = request;
	}

	public V1AdmissionReview response(V1AdmissionResponse response) {
		this.response = response;
		return this;
	}

	/**
	 * Get response
	 * 
	 * @return response
	 **/
	@Schema(description = "")
	public V1AdmissionResponse getResponse() {
		return response;
	}

	public void setResponse(V1AdmissionResponse response) {
		this.response = response;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		V1AdmissionReview v1AdmissionReview = (V1AdmissionReview) o;
		return Objects.equals(this.apiVersion, v1AdmissionReview.apiVersion)
				&& Objects.equals(this.kind, v1AdmissionReview.kind)
				&& Objects.equals(this.request, v1AdmissionReview.request)
				&& Objects.equals(this.response, v1AdmissionReview.response);
	}

	@Override
	public int hashCode() {
		return Objects.hash(apiVersion, kind, request, response);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class V1AdmissionReview {\n");

		sb.append("    apiVersion: ").append(toIndentedString(apiVersion)).append("\n");
		sb.append("    kind: ").append(toIndentedString(kind)).append("\n");
		sb.append("    request: ").append(toIndentedString(request)).append("\n");
		sb.append("    response: ").append(toIndentedString(response)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
