/*
 * k8s.io/api/admission/v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.sochovsky.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;

/**
 * GroupVersionResource unambiguously identifies a resource. It doesn&#x27;t
 * anonymously include GroupVersion to avoid automatic coersion. It doesn&#x27;t
 * use a GroupVersion to avoid custom marshalling
 */
@Data
@Schema(description = "GroupVersionResource unambiguously identifies a resource.  It doesn't anonymously include GroupVersion to avoid automatic coersion.  It doesn't use a GroupVersion to avoid custom marshalling")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-04-08T23:27:15.525561+02:00[Europe/Vienna]")
public class V1GroupVersionResource {
	@SerializedName("group")
	private String group = null;

	@SerializedName("resource")
	private String resource = null;

	@SerializedName("version")
	private String version = null;

	public V1GroupVersionResource group(String group) {
		this.group = group;
		return this;
	}

	/**
	 * Get group
	 * 
	 * @return group
	 **/
	@Schema(required = true, description = "")
	public String getGroup() {
		return group;
	}

	public void setGroup(String group) {
		this.group = group;
	}

	public V1GroupVersionResource resource(String resource) {
		this.resource = resource;
		return this;
	}

	/**
	 * Get resource
	 * 
	 * @return resource
	 **/
	@Schema(required = true, description = "")
	public String getResource() {
		return resource;
	}

	public void setResource(String resource) {
		this.resource = resource;
	}

	public V1GroupVersionResource version(String version) {
		this.version = version;
		return this;
	}

	/**
	 * Get version
	 * 
	 * @return version
	 **/
	@Schema(required = true, description = "")
	public String getVersion() {
		return version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		V1GroupVersionResource v1GroupVersionResource = (V1GroupVersionResource) o;
		return Objects.equals(this.group, v1GroupVersionResource.group)
				&& Objects.equals(this.resource, v1GroupVersionResource.resource)
				&& Objects.equals(this.version, v1GroupVersionResource.version);
	}

	@Override
	public int hashCode() {
		return Objects.hash(group, resource, version);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class V1GroupVersionResource {\n");

		sb.append("    group: ").append(toIndentedString(group)).append("\n");
		sb.append("    resource: ").append(toIndentedString(resource)).append("\n");
		sb.append("    version: ").append(toIndentedString(version)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
