apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dynamicscheduler
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["configmaps"]
  verbs: ["get", "patch", "create", "list", "delete"]
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "patch", "create", "list", "delete"]
- apiGroups: [""] # "" indicates the core API group
  resources: ["nodes"]
  verbs: ["get", "patch", "create", "list", "delete"]
- apiGroups: ["extensions","apps"] # "" indicates the apps API group
  resources: ["deployments"]
  verbs: ["get", "patch", "create", "list", "delete"]